# EDA for the latest version of Strucke Data

In this notebook the aim is to see the unique values of every row, see if there is anything to be manually resolver or mapped, and understand how much of the data needs cleaning. first a bit of brute force to see all the unique values for every column.

In [1]:
import pandas as pd

df = pd.read_csv("../data/StruckeC14_Sweden_v1.csv")
print(df.shape)
df.head()

(30301, 37)

,socken,landskap,place_name,raa_id,site_type,site_id,uppdragsnummer,lab_id,c14_age_bp,c14_error,...,cal_95_min,cal_95_max,median_cal_year,calibration_method,calibration_status,author,publication_year,title,journal,place_of_publication
0,Jörlanda,Bohuslän,Kyrkeby 3:34 m.fl.,Jörlanda 158,Boplats,L1969:5267,000103367,Ua-49252,2841.0,33.0,...,-913.0,-1110.0,-997.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Åberg, Joakim",2015.0,Bergsmonument och boplatser i Jörlanda,"Bohusläns museum Rapport, 2015:14",Uddevalla
1,Jörlanda,Bohuslän,Berg1:69,Jörlanda 185,Boplats,L1970:9431,NaN,T-8772,1720.0,80.0,...,541.0,132.0,339.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Johansson, Nils",1995.0,Tre boplatser i Spekerödsdalen,"UV Väst, Rapport 1995:1",Kungsbacka
2,Jörlanda,Bohuslän,Berg1:69,Jörlanda 185,Boplats,L1970:9431,NaN,T-8773,2890.0,105.0,...,-830.0,-1381.0,-1086.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Johansson, Nils",1995.0,Tre boplatser i Spekerödsdalen,"UV Väst, Rapport 1995:1",Kungsbacka
3,Jörlanda,Bohuslän,Berg1:69,Jörlanda 185,Boplats,L1970:9431,NaN,T-8774,2015.0,75.0,...,207.0,-333.0,-5.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Johansson, Nils",1995.0,Tre boplatser i Spekerödsdalen,"UV Väst, Rapport 1995:1",Kungsbacka
4,Jörlanda,Bohuslän,Berg1:69,Jörlanda 185,Boplats,L1970:9431,NaN,T-8775,1990.0,55.0,...,203.0,-144.0,29.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Johansson, Nils",1995.0,Tre boplatser i Spekerödsdalen,"UV Väst, Rapport 1995:1",Kungsbacka

In [3]:
col = "socken"
vc = df[col].value_counts(dropna=False).reset_index().sort_values(by=col)
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

socken: 1055 unique values

         socken  count
216       Abild     35
152      Adelsö     53
959   Agunnaryd      1
372         Ala     15
831      Alböke      2
..          ...    ...
284   Överkalix     25
483   Överluleå     10
674    Överselö      5
799  Övertorneå      3
226      Övraby     33

[1055 rows x 2 columns]

In [ ]:
col = "landskap"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

landskap: 36 unique values

         landskap  count
0         Uppland   6042
1           Skåne   4780
2    Östergötland   3212
3    Södermanland   2942
4         Halland   1835
5        Bohuslän   1773
6         Småland   1760
7           Närke   1321
8   Västergötland   1262
9     Västmanland   1247
10        Dalarna    669
11       Blekinge    563
12       Värmland    379
13     Norrbotten    328
14        Gotland    294
15       Lappland    293
16       Medelpad    269
17          Öland    236
18       Jämtland    214
19             Bo    173
20   Ångermanland    116
21     Härjedalen    108
22    Hälsingland     88
23    Gästrikland     83
24             Vg     81
25             Ha     79
26   Västerbotten     42
27             Sm     39
28             Sk     18
29       Dalsland     16
30             Sö     15
31             Nä     11
32             vg      5
33             Vs      3
34             Up      3
35             Ög      2

In [42]:
col = "place_name"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

place_name: 5001 unique values

               place_name  count
0        Lockarp 2:1 m fl    223
1          Spallationen 1    144
2             Rödbobacken    134
3              Akalla 4:1    118
4     Gamla Uppsala 21:52    115
...                   ...    ...
4996              Åby 2:1      1
4997            Valla 5:1      1
4998        Hunnebo 1:647      1
4999       Lyttersta 1:43      1
5000   Stora Kulltorp 2:2      1

[5001 rows x 2 columns]

In [43]:
col = "raa_id"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

raa_id: 5439 unique values

           raa_id  count
0             NaN   1841
1      Lockarp 18    223
2     Skänninge 5    121
3        Härad 82    119
4     Uppsala 614    107
...           ...    ...
5434   L2020:4793      1
5435          671      1
5436    L2018:146      1
5437   L2022:7402      1
5438    L2023:390      1

[5439 rows x 2 columns]

In [44]:
col = "site_type"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

site_type: 304 unique values

                   site_type  count
0                    Boplats   8449
1              Boplatsområde   6877
2    Grav- och boplatsområde   3390
3                   Gravfält   1884
4                Fossil åker   1059
..                       ...    ...
299       Gravfält, boplats,      1
300                     Grop      1
301    Boplatslämnuing övrig      1
302                Tegelbruk      1
303             Kyrka kapell      1

[304 rows x 2 columns]

In [45]:
col = "site_id"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

site_id: 6120 unique values

         site_id  count
0            NaN    338
1     L1988:4693    223
2      L2010:586    120
3     L1984:2122    119
4     L1941:4268    107
...          ...    ...
6115  L2020:4793      1
6116  L1982:4609      1
6117   L2018:146      1
6118  L2022:7402      1
6119   L2023:390      1

[6120 rows x 2 columns]

In [46]:
col = "uppdragsnummer"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

uppdragsnummer: 2876 unique values

     uppdragsnummer  count
0               NaN  13050
1         201901401    274
2         201700787    148
3         200800086    101
4         200100306    101
...             ...    ...
2871      202400331      1
2872      201400904      1
2873      200900594      1
2874      202000714      1
2875      200800209      1

[2876 rows x 2 columns]

In [47]:
col = "lab_id"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

lab_id: 30291 unique values

            lab_id  count
0         Ua-86040      3
1         Ua-10042      2
2         Ua-78697      2
3        Ua-26675a      2
4         Ua-43186      2
...            ...    ...
30286     LuS-6339      1
30287     16C/0261      1
30288  Beta-511943      1
30289     Ua-76281      1
30290     Ua-76282      1

[30291 rows x 2 columns]

In [48]:
col = "c14_age_bp"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

c14_age_bp: 4845 unique values

      c14_age_bp  count
0            NaN    345
1          250.0    179
2         1700.0     98
3         1740.0     89
4         1690.0     81
...          ...    ...
4840      8395.0      1
4841      2298.0      1
4842      2889.0      1
4843       909.0      1
4844     14575.0      1

[4845 rows x 2 columns]

In [49]:
col = "c14_error"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

c14_error: 223 unique values

     c14_error  count
0         30.0   5289
1         70.0   2155
2         40.0   1910
3         35.0   1862
4         60.0   1689
..         ...    ...
218      147.0      1
219      131.0      1
220      112.0      1
221      143.0      1
222        2.0      1

[223 rows x 2 columns]

In [50]:
col = "d13C"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

d13C: 730 unique values

       d13C  count
0       NaN  15862
1    -25.40    351
2    -25.60    344
3    -26.10    341
4    -26.40    328
..      ...    ...
725  -30.79      1
726  -25.14      1
727  -24.78      1
728 -224.40      1
729  -17.70      1

[730 rows x 2 columns]

In [51]:
col = "pMC_value"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

pMC_value: 73 unique values

    pMC_value  count
0         NaN  30201
1       100.0      5
2        99.3      4
3       101.6      3
4        99.5      3
..        ...    ...
68      119.9      1
69      109.1      1
70      104.7      1
71      106.9      1
72      144.6      1

[73 rows x 2 columns]

In [52]:
col = "pMC_error"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

pMC_error: 21 unique values

    pMC_error  count
0         NaN  30202
1        0.40     29
2        0.50     19
3        0.80     10
4        0.60      8
5        0.30      7
6        0.70      6
7        0.90      5
8        1.00      2
9        1.60      2
10       0.55      1
11       0.43      1
12      11.00      1
13       0.34      1
14       1.50      1
15       0.52      1
16       1.10      1
17       0.41      1
18       1.20      1
19      30.00      1
20       0.00      1

In [53]:
col = "c14_data_status"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

c14_data_status: 4 unique values

             c14_data_status  count
0                         ok  29731
1            c14_data_saknas    470
2  modern date, no c14 data.     99
3     orealistiskt_c14_värde      1

In [54]:
col = "comment"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

comment: 2058 unique values

                                                comment  count
0                                                   NaN  26619
1                               Daterar ej anläggningen    188
2         Viss oklarhet om vilket material som daterats     46
3                            14C-ålder saknas i rapport     37
4                                      Daterar ej huset     30
...                                                 ...    ...
2053  14C-ålder saknas i rapport. Kal. 2 sigma 1375-...      1
2054  14C-ålder saknas i rapport kal. 2 sigma 1730-1...      1
2055   Labnr saknas i rapport Kal. 2 sigma 1680-1515 BC      1
2056  14C-ålder saknas i rapport kaol. 2 sigma 1670-...      1
2057      14C-ålder saknas i  rapport Kal. 1690-1510 BC      1

[2058 rows x 2 columns]

In [55]:
col = "assessed_relevant"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

assessed_relevant: 4 unique values

  assessed_relevant  count
0                 J  28364
1                 N   1506
2                 X    235
3               NaN    196

In [56]:
col = "material"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

material: 42 unique values

                       material  count
0                        träkol  21891
1                 förkolnat frö   2667
2                  ben, obrända   1245
3                   ben, brända   1133
4                           trä   1087
5                  skalfragment    551
6           organisk beläggning    385
7                     växtdelar    334
8                          bark    302
9                         harts    253
10                         tand    155
11           frö (ej förkolnat)     36
12                    animalier     33
13                   kol i järn     30
14                     karbonat     27
15                        humus     24
16                        okänd     22
17                         horn     21
18                         torv     17
19                   sotig jord     17
20           organiskt material     15
21                         bröd      6
22                         kåda      6
23                     sediment      6
24                        mossa      5
25       sot/organiskt material      5
26           trä/bark/växtdelar      3
27                     kollagen      3
28                    förkolnad      3
29               skal/mollusker      3
30  ben, obränt karbonat frakt.      2
31                       pollen      2
32                    järnslagg      2
33                     ben,horn      2
34                     fekalier      1
35                        svamp      1
36                       gyttja      1
37                                   1
38                      stenkol      1
39              krossad keramik      1
40                         fisk      1
41                      kol/sot      1

In [57]:
col = "species"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

species: 544 unique values

               species  count
0                  NaN  12064
1                 tall   2929
2                björk   1955
3                   ek   1736
4               hassel   1649
..                 ...    ...
539     cf. Betula sp.      1
540         bark/näver      1
541        Populus sp.      1
542  Cyperaceae, snöre      1
543              haver      1

[544 rows x 2 columns]

In [58]:
col = "context_id"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

context_id: 10506 unique values

      context_id  count
0            NaN   4266
1             A1    718
2             A2    462
3             A3    333
4             A4    258
...          ...    ...
10501     A50440      1
10502     A50526      1
10503      A5836      1
10504      A5909      1
10505      A8793      1

[10506 rows x 2 columns]

In [10]:
col = "context_type"
vc = df[col].value_counts(dropna=False).reset_index().sort_values(by=col)
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

context_type: 962 unique values

         context_type  count
181   aktivitetslager      9
188     aktivitetsyta      8
469            ankare      2
337        anläggning      3
878  annan anläggning      1
..                ...    ...
304          åkervall      3
874           åkeryta      1
197         årderspår      7
925  östra golvgropen      1
7                 NaN    508

[962 rows x 2 columns]

In [60]:
col = "northing_3006"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

northing_3006: 6173 unique values

      northing_3006  count
0           6157001    223
1           6472725    120
2           6581472    119
3           6642663    107
4           6642832    106
...             ...    ...
6168        6482458      1
6169        6538022      1
6170        6543544      1
6171        6543568      1
6172        6543765      1

[6173 rows x 2 columns]

In [61]:
col = "easting_3006"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

easting_3006: 6149 unique values

      easting_3006  count
0           375846    223
1           505067    120
2           607657    119
3           648609    107
4           647453    106
...            ...    ...
6144        284212      1
6145        551529      1
6146        564279      1
6147        550473      1
6148        550513      1

[6149 rows x 2 columns]

In [62]:
col = "longitude"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

longitude: 6212 unique values

      longitude  count
0     13.032330    223
1     15.086680    120
2     16.893721    119
3     17.656345    107
4     17.635827    106
...         ...    ...
6207  11.303832      1
6208  15.896363      1
6209  16.119718      1
6210  15.879265      1
6211  15.880007      1

[6212 rows x 2 columns]

In [63]:
col = "latitude"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

latitude: 6211 unique values

       latitude  count
0     55.543218    223
1     58.395302    120
2     59.358220    119
3     59.894680    107
4     59.896610    106
...         ...    ...
6206  58.429458      1
6207  58.978667      1
6208  59.026524      1
6209  59.028593      1
6210  59.030358      1

[6211 rows x 2 columns]

In [64]:
col = "location_precision"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

location_precision: 2 unique values

    location_precision  count
0  archaeological site  29963
1               parish    338

In [65]:
col = "cal_68_min"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

cal_68_min: 2837 unique values

      cal_68_min  count
0            NaN    570
1         1950.0    542
2          773.0    276
3          772.0    254
4          534.0    176
...          ...    ...
2832     -7953.0      1
2833     -7683.0      1
2834     -7362.0      1
2835     -7587.0      1
2836    -15826.0      1

[2837 rows x 2 columns]

In [66]:
col = "cal_68_max"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

cal_68_max: 2936 unique values

      cal_68_max  count
0            NaN    570
1          775.0    411
2          776.0    276
3          266.0    224
4          435.0    199
...          ...    ...
2931     -8160.0      1
2932     -8226.0      1
2933     -7588.0      1
2934     -7537.0      1
2935    -15989.0      1

[2936 rows x 2 columns]

In [67]:
col = "cal_95_min"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

cal_95_min: 2810 unique values

      cal_95_min  count
0         1950.0   1020
1            NaN    570
2          773.0    313
3          772.0    171
4          402.0    167
...          ...    ...
2805     -7533.0      1
2806     -7600.0      1
2807     -7581.0      1
2808     -1417.0      1
2809    -15616.0      1

[2810 rows x 2 columns]

In [68]:
col = "cal_95_max"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

cal_95_max: 2904 unique values

      cal_95_max  count
0            NaN    570
1          775.0    297
2          776.0    280
3          434.0    147
4          250.0    125
...          ...    ...
2899     -8545.0      1
2900     -8204.0      1
2901     -8200.0      1
2902     -8254.0      1
2903    -16071.0      1

[2904 rows x 2 columns]

In [69]:
col = "median_cal_year"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

median_cal_year: 5798 unique values

      median_cal_year  count
0                 NaN    570
1              1562.0    155
2              1347.0    107
3              -277.0    106
4              -276.0    100
...               ...    ...
5793          -7644.0      1
5794          -1738.0      1
5795           -416.0      1
5796         -15902.0      1
5797          -1546.0      1

[5798 rows x 2 columns]

In [70]:
col = "calibration_method"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

calibration_method: 2 unique values

             calibration_method  count
0  HPD; IntCal20; rcarbon 1.5.0  29731
1                           NaN    570

In [71]:
col = "calibration_status"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

calibration_status: 3 unique values

  calibration_status  count
0         calibrated  29731
1   not calibratable    569
2  not yet attempted      1

In [72]:
col = "author"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

author: 1898 unique values

                                      author  count
0                                  Protokoll    485
1                              Strömberg, Bo    277
2                          Olausson, Michael    261
3                              Carlsson, Tom    208
4                             Åstrand, Johan    178
...                                      ...    ...
1893       Ängeby, Gisela & Nordqvist, Bengt      1
1894  Bramstång, Carina & Gustafsson, Agneta      1
1895                           Pye, Jonathan      1
1896          Vajking, Erik & Swedberg, Stig      1
1897  Larsson, G., Sundström, L & Guinard, M      1

[1898 rows x 2 columns]

In [73]:
col = "publication_year"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

publication_year: 67 unique values

    publication_year  count
0             2006.0   1555
1             2014.0   1321
2             2005.0   1283
3             1996.0   1261
4             2017.0   1196
..               ...    ...
62            1985.0      6
63             198.0      4
64            1966.0      4
65             200.0      4
66             201.0      1

[67 rows x 2 columns]

In [74]:
col = "title"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

title: 4497 unique values

                                                  title  count
0                                       C-14 Dateringar    485
1     Järnhantering på boplatser i Halland under äld...    236
2     Norra Spånga. Bebyggelse och samhälle under jä...    149
3     Östra Odarslöv 13:5, ESS-området Forntid möter...    148
4     Det inneslutna rummet-om kultiska hägnader, fo...    145
...                                                 ...    ...
4492  Tossene 371 och 1042. Tossene socken, Sotenäs ...      1
4493  Klippöverhäng och stenåldersboplats vid Åby sä...      1
4494  Tossene 137 och 576 inom Valla 4:7 och 5:1, To...      1
4495  Tossene L2020:4793 och L2020:4796, Sotenäs kom...      1
4496  Stockbåten i Lyttersta. Arkeologisk dokumentat...      1

[4497 rows x 2 columns]

In [75]:
col = "journal"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

journal: 4299 unique values

                                                journal  count
0                                               Stencil    546
1                                                   NaN    468
2         Nya bidrag till Hallands äldsta historia nr 4    236
3                          Stockholmsmonografier vol 76    149
4                         Arkeologerna, Rapport 2017:11    148
...                                                 ...    ...
4294                Kulturlandskapet rapporter, 2014:13      1
4295                      UV Väst, Internrapport 1993:4      1
4296  Rio Kulturkooperativ, Kulturhistoriska rapport...      1
4297                Kulturlandskapet rapporter, 2020:14      1
4298                                 SAU Rapport 2008:7      1

[4299 rows x 2 columns]

In [76]:
col = "place_of_publication"
vc = df[col].value_counts(dropna=False).reset_index()
vc.columns = [col, "count"]
print(f"{col}: {len(vc)} unique values")
vc

place_of_publication: 141 unique values

             place_of_publication  count
0                       Stockholm   6400
1                         Uppsala   3106
2                            Lund   2814
3                       Linköping   2553
4                        Västerås   1314
..                            ...    ...
136                         Örero      1
137                    Skellefteå      1
138                      Arjeplog      1
139  Uppsala. Rapport 2: Uppsala.      1
140                     Västeråsd      1

[141 rows x 2 columns]

### Look for rows with more than one site_id in the value

In [9]:
df[df['site_id'].isin(['L1988:6073, L1988:6685','L1983:7553, L1983:7552, L1983:8196, L1983:7619'])]

,socken,landskap,place_name,raa_id,site_type,site_id,uppdragsnummer,lab_id,c14_age_bp,c14_error,...,cal_95_min,cal_95_max,median_cal_year,calibration_method,calibration_status,author,publication_year,title,journal,place_of_publication
2062,Åker,Södermanland,Järsta 1:3,Åker 267,Boplats,"L1983:7553, L1983:7552, L1983:8196, L1983:7619",NaN,ST13672,1940.0,60.0,...,230.0,-44.0,89.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Franzén, Bitte & Schützler, Lillemor",2000.0,Fornlämningar vid Albertsro.,"UV Mitt, Rapport 2000:37",Stockholm
2063,Åker,Södermanland,Järsta 1:3,Åker 267,Boplats,"L1983:7553, L1983:7552, L1983:8196, L1983:7619",NaN,ST13673,1870.0,60.0,...,329.0,19.0,168.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Franzén, Bitte & Schützler, Lillemor",2000.0,Fornlämningar vid Albertsro.,"UV Mitt, Rapport 2000:37",Stockholm
2064,Åker,Södermanland,Järsta 1:3,Åker 267,Boplats,"L1983:7553, L1983:7552, L1983:8196, L1983:7619",NaN,ST13675,1790.0,45.0,...,400.0,130.0,283.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Franzén, Bitte & Schützler, Lillemor",2000.0,Fornlämningar vid Albertsro.,"UV Mitt, Rapport 2000:37",Stockholm
2065,Åker,Södermanland,Järsta 1:3,Åker 267,Boplats,"L1983:7553, L1983:7552, L1983:8196, L1983:7619",NaN,ST13676,2130.0,40.0,...,-44.0,-351.0,-151.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Franzén, Bitte & Schützler, Lillemor",2000.0,Fornlämningar vid Albertsro.,"UV Mitt, Rapport 2000:37",Stockholm
2094,Åker,Södermanland,Järsta 1:3,Åker 267,Boplats,"L1983:7553, L1983:7552, L1983:8196, L1983:7619",NaN,ST14211,1545.0,45.0,...,601.0,421.0,518.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Franzén, Bitte & Schützler, Lillemor",2000.0,Fornlämningar vid Albertsro.,"UV Mitt, Rapport 2000:37",Stockholm
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26390,Stora Herrestad,Skåne,Herrestad 68:88 m fl,"Stora Herrestad 60:1, 60:2",Boplatsområde,"L1988:6073, L1988:6685",000100475,Ua-7927,2025.0,70.0,...,202.0,-338.0,-17.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Andersson, Magnus m fl",1999.0,Boplats stenålder-äldre järnålder.,"UV Syd, Rapport 1999:8",Lund
26391,Stora Herrestad,Skåne,Herrestad 68:88 m fl,"Stora Herrestad 60:1, 60:2",Boplatsområde,"L1988:6073, L1988:6685",000100475,Ua-7928,1930.0,65.0,...,242.0,-48.0,100.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Andersson, Magnus m fl",1999.0,Boplats stenålder-äldre järnålder.,"UV Syd, Rapport 1999:8",Lund
26392,Stora Herrestad,Skåne,Herrestad 68:88 m fl,"Stora Herrestad 60:1, 60:2",Boplatsområde,"L1988:6073, L1988:6685",000100475,Ua-7929,4055.0,80.0,...,-2350.0,-2878.0,-2612.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Andersson, Magnus m fl",1999.0,Boplats stenålder-äldre järnålder.,"UV Syd, Rapport 1999:8",Lund
26393,Stora Herrestad,Skåne,Herrestad 68:88 m fl,"Stora Herrestad 60:1, 60:2",Boplatsområde,"L1988:6073, L1988:6685",000100475,Ua-7930,3285.0,70.0,...,-1421.0,-1738.0,-1562.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Andersson, Magnus m fl",1999.0,Boplats stenålder-äldre järnålder.,"UV Syd, Rapport 1999:8",Lund
26394,Stora Herrestad,Skåne,Herrestad 68:88 m fl,"Stora Herrestad 60:1, 60:2",Boplatsområde,"L1988:6073, L1988:6685",000100475,Ua-7931,3435.0,145.0,...,-1425.0,-2135.0,-1750.0,HPD; IntCal20; rcarbon 1.5.0,calibrated,"Andersson, Magnus m fl",1999.0,Boplats stenålder-äldre järnålder.,"UV Syd, Rapport 1999:8",Lund

## Tasks To Be Done

### Pre-ShapeShifter

- split `site_id` by commas, rename columns to avoid `_id`.
- manual map of the unusable values of `landskap`.
- split `uppdragsnummer` by commas.
- Extract lab prefixes from `lab_id` in a new column. 
- Standarize lab prefixes according to lab pdf or SEAD's.

**To be asked:** 
1. Possible split in the `context_type` for adjectives in a similar feature (see df printed for context_type: "stensättning" appears multiple times with different descriptions like "oval", "rund", "avlång", etc.) 
2. translate `context_type` values (they are in swedish and `tbl_feature_types.feature_type_name` is in english)  

### In ShapeShifter

- Create a column from northing_3006 and easting_3006 with values like f'({str(northing_3006)}, {str(easting_3006)})'
- Create full reference
- Create dataset

**To be asked:**

1. How to handle `lab_id` being almos unique to every row. Should we create a dataset for every one of those?
2. How to create the dataset, sample groups, physical samples, analysis entities, etc.